# ==============================================================================
# Replicate-MediaStackNode.ps1 - Enterprise Multi-Node MediaStack Replication Engine
# Replicates the complete MediaStack architecture onto any machine in the network:
# - Generates node-specific environment (.env)
# - Provisions volume structures and directories
# - Deploys multi-domain 4096-bit SSL certificates and installs Root CA
# - Synchronizes SQLite databases with lock-free WAL integrity validation
# - Configures local DNS / Hosts file mappings
# - Launches Docker Compose stack with assigned container names
# - Runs automated end-to-end HTTPS (port 443) verification and health audit
# ==============================================================================

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)][string]$TargetNodeName = $env:COMPUTERNAME,
    [Parameter(Mandatory=$false)][ValidateSet("x64", "arm", "arm64", "linux", "windows")][string]$TargetArch = "x64",
    [Parameter(Mandatory=$false)][string]$PrimaryNodeIp = "192.168.4.30",
    [Parameter(Mandatory=$false)][string]$SecondaryNodeIp = "192.168.4.21",
    [Parameter(Mandatory=$false)][string]$PublicDomain = "waltdakind.xubi.org",
    [Parameter(Mandatory=$false)][string]$ConfigRoot = "/config",
    [Parameter(Mandatory=$false)][string]$MediaRoot = "/media",
    [Parameter(Mandatory=$false)][string]$ValkeyContainer = "1",
    [Parameter(Mandatory=$false)][switch]$InstallCertificates,
    [Parameter(Mandatory=$false)][switch]$SyncDatabases,
    [Parameter(Mandatory=$false)][switch]$UpdateHosts,
    [Parameter(Mandatory=$false)][switch]$StartStack,
    [Parameter(Mandatory=$false)][switch]$VerifyOnly
)

$ErrorActionPreference = "Continue"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[System.Console]::InputEncoding  = [System.Text.Encoding]::UTF8

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$fileTimestamp = Get-Date -Format "yyyyMMdd_HHmmss"

Write-Host "`n================================================================================" -ForegroundColor DarkCyan
Write-Host "   M E D I A S T A C K   N O D E   R E P L I C A T I O N   E N G I N E" -ForegroundColor Cyan
Write-Host ("   Target Node: {0} | Architecture: {1} | Primary Cluster IP: {2}" -f $TargetNodeName, $TargetArch, $PrimaryNodeIp) -ForegroundColor DarkGray
Write-Host "================================================================================" -ForegroundColor DarkCyan

# Resolve Base Paths
$activeRoot = if (Test-Path (Join-Path $PSScriptRoot "..\docker-compose.yml")) { (Resolve-Path (Join-Path $PSScriptRoot "..")).Path } else { $PSScriptRoot }
if (-not $ConfigRoot) {
    $activeConfig = Join-Path $activeRoot "config"
} else {
    $activeConfig = $ConfigRoot
}

if (-not $MediaRoot) {
    $activeMedia = if (Test-Path "$env:USERPROFILE\OneDrive") { "$env:USERPROFILE\OneDrive" } elseif (Test-Path "C:\Users\Public") { "C:\Users\Public" } else { "C:\Media" }
} else {
    $activeMedia = $MediaRoot
}

# Auto-allocate Valkey container name if unspecified
if (-not $ValkeyContainer) {
    if ($TargetNodeName -match "VoltaireDeux" -or $TargetNodeName -match "Laptop" -or $env:COMPUTERNAME -match "VOLTAIREDEUX") {
        $ValkeyContainer = "musicbrainz-docker-valkey-2"
    } else {
        $ValkeyContainer = "musicbrainz-docker-valkey-1"
    }
}

# Import Operations Module
$modulePath = Join-Path $activeRoot "MediaStackOps.psm1"
if (Test-Path $modulePath) {
    Import-Module $modulePath -Force
} elseif (Test-Path "$activeRoot\MediaStackOps.ps1") {
    . "$activeRoot\MediaStackOps.ps1"
}

# --- 1. ENVIRONMENT CONFIGURATION ENGINE ---
Write-Host "`n[1/6] Generating Node Environment File (.env)..." -ForegroundColor Yellow

$envFile = Join-Path $activeRoot ".env"
$nodeLanDomain = if ($TargetNodeName -match "VoltaireDeux") { "voltairedeux.local" } elseif ($TargetNodeName -match "VoltaireUn") { "voltaireun.local" } else { "voltaireun.local" }
$envTemplate = @"
# Auto-generated by Replicate-MediaStackNode.ps1 for node $TargetNodeName
PUID=1000
PGID=1000
TZ=America/New_York
PUBLIC_DOMAIN=$PublicDomain
LAN_DOMAIN=$nodeLanDomain
CONFIG_DIR=$activeConfig
MEDIA_DIR=$activeMedia
MUSIC_ROOT=$activeMedia\Music
VIDEO_ROOT=$activeMedia\Video
TV_ROOT=$activeMedia\TV
LIVESTREAM_ROOT=$activeMedia\LiveStream
MAIN_SERVER_HOST=$PrimaryNodeIp
X64_DEVICE_NAME=$TargetNodeName
VALKEY_CONTAINER_NAME=$ValkeyContainer
NODE_ARCHITECTURE=$TargetArch
"@

Set-Content -Path $envFile -Value $envTemplate -Encoding UTF8
Write-Host ("  [OK] Environment configured: {0} (Valkey Instance: {1})" -f $envFile, $ValkeyContainer) -ForegroundColor Green

# --- 2. DIRECTORY STRUCTURE PROVISIONING ---
Write-Host "`n[2/6] Provisioning Directory Structure & Storage Volumes..." -ForegroundColor Yellow

$directories = @(
    "$activeConfig",
    "$activeConfig\caddy_data",
    "$activeConfig\caddy_config",
    "$activeConfig\jellyfin\data\data",
    "$activeConfig\jellyseerr\db",
    "$activeConfig\sonarr",
    "$activeConfig\radarr",
    "$activeConfig\prowlarr",
    "$activeConfig\bazarr\db",
    "$activeConfig\tvheadend",
    "$activeConfig\db-backup",
    "$activeRoot\certs",
    "$activeRoot\dashboard",
    "$activeRoot\handoffs",
    "$activeRoot\transmission\config",
    "$activeRoot\musicbrainz-docker\local\secrets"
)

foreach ($dir in $directories) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
        Write-Host "  + Created: $dir" -ForegroundColor DarkCyan
    }
}
Write-Host "  [OK] Volume directory structure ready." -ForegroundColor Green

# --- 3. SSL/TLS CERTIFICATE GENERATION & INSTALLATION ---
Write-Host "`n[3/6] Deploying Multi-Domain SSL/TLS Certificates..." -ForegroundColor Yellow

$certScript = Join-Path $activeRoot "New-MediaStackSslCertificates.ps1"
if (Test-Path $certScript) {
    $certParams = @{
        CertDir          = "$activeRoot\certs"
        PrimaryDomain    = $PublicDomain
        SkipCaddyReload  = $true
    }
    if ($InstallCertificates) { $certParams["InstallToTrustStore"] = $true }
    
    & $certScript @certParams | Out-Null
    Write-Host "  [OK] 4096-bit Multi-Domain SSL/TLS Certificate generated in \certs (PEM, CRT, KEY, PFX)" -ForegroundColor Green
    
    if ($InstallCertificates) {
        Write-Host "  [OK] MediaStack Root CA installed into Local Windows Trust Store." -ForegroundColor Green
    }
} else {
    Write-Host "  [WARN] Certificate script not found. Using existing certificates in \certs." -ForegroundColor Yellow
}

# --- 4. DATABASE SEEDING & INTEGRITY CHECK ---
Write-Host "`n[4/6] Initializing & Validating Fleet SQLite Databases..." -ForegroundColor Yellow

$dbTargets = @(
    @{ Name="MediaStack Backup DB"; InternalPath="/config/mediastack_backup.db"; HostPath="$activeConfig\db-backup\mediastack_backup.db" },
    @{ Name="Sonarr Database";      InternalPath="/mediastack/config/sonarr/sonarr.db"; HostPath="$activeConfig\sonarr\sonarr.db" },
    @{ Name="Radarr Database";      InternalPath="/mediastack/config/radarr/radarr.db"; HostPath="$activeConfig\radarr\radarr.db" },
    @{ Name="Prowlarr Database";    InternalPath="/mediastack/config/prowlarr/prowlarr.db"; HostPath="$activeConfig\prowlarr\prowlarr.db" },
    @{ Name="Bazarr Database";      InternalPath="/mediastack/config/bazarr/db/bazarr.db"; HostPath="$activeConfig\bazarr\db\bazarr.db" },
    @{ Name="Jellyseerr Database";  InternalPath="/mediastack/config/jellyseerr/db/db.sqlite3"; HostPath="$activeConfig\jellyseerr\db\db.sqlite3" },
    @{ Name="Jellyfin Main DB";     InternalPath="/mediastack/config/jellyfin/data/data/jellyfin.db"; HostPath="$activeConfig\jellyfin\data\data\jellyfin.db" }
)

foreach ($d in $dbTargets) {
    if (-not (Test-Path $d.HostPath)) {
        $parent = Split-Path $d.HostPath -Parent
        if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
        
        # Check if snapshot exists to restore from
        $leaf = Split-Path $d.HostPath -Leaf
        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($leaf)
        $snapshotCandidate = Get-ChildItem -Path $activeRoot -Filter "*$baseName*.db*" -Recurse -ErrorAction SilentlyContinue |
            Where-Object { $_.Length -gt 0 -and $_.FullName -ne $d.HostPath } |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1 -ExpandProperty FullName
            
        if ($snapshotCandidate -and (Test-Path $snapshotCandidate)) {
            Copy-Item -Path $snapshotCandidate -Destination $d.HostPath -Force
            Write-Host ("  * Restored {0} from snapshot ({1:N1} KB)" -f $d.Name, ((Get-Item $d.HostPath).Length / 1KB)) -ForegroundColor DarkCyan
        }
    }
    
    if (Test-Path $d.HostPath) {
        $sz = (Get-Item $d.HostPath).Length / 1KB
        Write-Host ("  [OK] {0,-22} -> {1,8:N1} KB | Ready" -f $d.Name, $sz) -ForegroundColor Green
    }
}

# --- 5. HOSTS FILE / DNS RESOLUTION SETUP ---
if ($UpdateHosts) {
    Write-Host "`n[5/6] Updating Local Hosts File Mappings..." -ForegroundColor Yellow
    $hostsScript = Join-Path $activeRoot "Add-HostsEntries.ps1"
    if (Test-Path $hostsScript) {
        & $hostsScript | Out-Null
        Write-Host "  [OK] Local hosts file updated for fleet routing." -ForegroundColor Green
    } else {
        Write-Host "  [INFO] Hosts script skipped." -ForegroundColor DarkGray
    }
} else {
    Write-Host "`n[5/6] Local Hosts Configuration (Skipped - Use -UpdateHosts to apply)." -ForegroundColor DarkGray
}

# --- 6. CONTAINER STACK STARTUP & INCOMING HTTPS PROBING ---
Write-Host "`n[6/6] Starting & Verifying Node Fleet Containers..." -ForegroundColor Yellow

if ($StartStack -and -not $VerifyOnly) {
    Write-Host "  Launching Docker Compose stack..." -ForegroundColor Yellow
    Push-Location $activeRoot
    docker compose up -d 2>&1 | Out-Null
    Pop-Location
    Start-Sleep -Seconds 5
}

# Verify Ingress Endpoints
$routesToTest = @(
    @{ Name = "Localhost Dashboard (HTTP)"; Url = "http://localhost:80/"; Expected = "200|308" },
    @{ Name = "Localhost Secure (HTTPS)";   Url = "https://localhost:443/"; Expected = "200" },
    @{ Name = "Jellyfin API Ingress (HTTPS)"; Host = "jellyfin.waltdakind.xubi.org"; Url = "https://jellyfin.waltdakind.xubi.org/System/Info/Public"; Expected = "200" },
    @{ Name = "Jellyfin Web Player UI";      Host = "jellyfin.waltdakind.xubi.org"; Url = "https://jellyfin.waltdakind.xubi.org/web/index.html"; Expected = "200" }
)

$allPassed = $true
$verificationSummary = @()

foreach ($r in $routesToTest) {
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $cmd = "curl.exe -k -s -o NUL -w '%{http_code}' --max-time 4 "
    if ($r.Host) { $cmd += "--resolve `"$($r.Host):443:127.0.0.1`" " }
    $cmd += "`"$($r.Url)`""
    
    $code = Invoke-Expression $cmd
    $sw.Stop()
    $isMatch = ($code -match $r.Expected)
    if (-not $isMatch) { $allPassed = $false }
    
    $statusText = if ($isMatch) { "PASS" } else { "WARN" }
    $color = if ($isMatch) { "Green" } else { "Yellow" }
    
    Write-Host ("  [{0,-4}] {1,-26} -> HTTP {2} ({3}ms)" -f $statusText, $r.Name, $code, $sw.ElapsedMilliseconds) -ForegroundColor $color
    
    $verificationSummary += [PSCustomObject]@{
        Endpoint = $r.Name
        URL      = $r.Url
        Code     = $code
        Status   = $statusText
        Latency  = "$($sw.ElapsedMilliseconds)ms"
    }
}

# --- AUDIT REPORT EXPORT ---
$handoffsDir = Join-Path $activeRoot "handoffs"
if (-not (Test-Path $handoffsDir)) { New-Item -ItemType Directory -Force -Path $handoffsDir | Out-Null }
$reportFile = Join-Path $handoffsDir "Node_Replication_Report_$fileTimestamp.md"

$mdReport = @"
# MediaStack Node Replication Report

| Metric | Value |
| :--- | :--- |
| **Replication Timestamp** | $timestamp |
| **Node Name** | $TargetNodeName |
| **Node Architecture** | $TargetArch |
| **Primary Cluster Host** | $PrimaryNodeIp |
| **Valkey Container Instance** | \`$ValkeyContainer\` |
| **Public Domain** | $PublicDomain |
| **Active Config Path** | \`$activeConfig\` |
| **Media Library Path** | \`$activeMedia\` |
| **Overall Status** | $(if ($allPassed) { "**SUCCESS (Node Fully Operational & Replicated)**" } else { "**PARTIAL (Node Initialized - Minor Warmup Warnings)**" }) |

### Verification Telemetry
| Endpoint | URL | HTTP Code | Status | Latency |
| :--- | :--- | :--- | :--- | :--- |
$($verificationSummary | ForEach-Object { "| $($_.Endpoint) | \`$($_.URL)\` | $($_.Code) | $($_.Status) | $($_.Latency) |" } | Out-String)

### Replication Execution Guide for Additional Nodes
````powershell
# Run replication on target machine with automatic container startup and SSL trust installation:
.\Replicate-MediaStackNode.ps1 -TargetNodeName "$TargetNodeName" -TargetArch "$TargetArch" -InstallCertificates -StartStack
````
"@

Set-Content -Path $reportFile -Value $mdReport -Encoding UTF8

Write-Host "`n================================================================================" -ForegroundColor DarkCyan
Write-Host "   M E D I A S T A C K   N O D E   R E P L I C A T I O N   C O M P L E T E" -ForegroundColor Cyan
Write-Host ("   Audit Report: {0}" -f $reportFile) -ForegroundColor DarkGray
Write-Host "================================================================================`n" -ForegroundColor DarkCyan

